import { test, describe } from "node:test";
import assert from "node:assert";
import { generateMarkdownExport } from "../src/lib/export-chat";
import { ChatMessage } from "../src/hooks/useChatStream";

describe("export-chat: generateMarkdownExport", () => {
  test("generates markdown transcript with metadata header and disclaimer", () => {
    const messages: ChatMessage[] = [
      {
        id: "m1",
        role: "user",
        content: "What is the liability cap under Section 9?",
        timestamp: "2026-09-16T10:00:00Z",
      },
      {
        id: "m2",
        role: "assistant",
        content: "The liability cap is strictly $1,000,000 as stated in Section 9.1 [^1].",
        timestamp: "2026-09-16T10:00:02Z",
        citations: [
          {
            source_index: 1,
            document_id: "doc-123",
            document_name: "Master_Services_Agreement.pdf",
            page_number: 9,
            snippet: "Aggregate liability shall not exceed $1,000,000 USD.",
            relevance_score: 0.95,
            verified: true,
          },
        ],
      },
    ];

    const md = generateMarkdownExport({
      messages,
      workspaceId: "ws-test",
      sessionTitle: "MSA Review Session",
      pipelineMode: "fast",
      groundingMode: "strict",
    });

    assert.match(md, /# MSA Review Session/);
    assert.match(md, /`ws-test`/);
    assert.match(md, /`fast`/);
    assert.match(md, /`strict`/);
    assert.match(md, /Turn 1: Question/);
    assert.match(md, /What is the liability cap under Section 9\?/);
    assert.match(md, /The liability cap is strictly \$1,000,000/);
    assert.match(md, /Master_Services_Agreement\.pdf/);
    assert.match(md, /✅ Verified/);
    assert.match(md, /Aggregate liability shall not exceed \$1,000,000 USD\./);
    assert.match(md, /Generated by TitanRAG Enterprise Knowledge Engine/);
  });

  test("handles empty messages gracefully", () => {
    const md = generateMarkdownExport({
      messages: [],
      workspaceId: "ws-empty",
    });

    assert.match(md, /Total Turns/);
    assert.match(md, /Generated by TitanRAG Enterprise Knowledge Engine/);
  });
});
