import { ChatMessage } from "../hooks/useChatStream";

export interface ExportChatOptions {
  messages: ChatMessage[];
  workspaceId?: string;
  sessionTitle?: string;
  pipelineMode?: string;
  groundingMode?: string;
}

export function generateMarkdownExport({
  messages,
  workspaceId = "default",
  sessionTitle = "TitanRAG Chat Session",
  pipelineMode = "auto",
  groundingMode = "balanced",
}: ExportChatOptions): string {
  const timestamp = new Date().toISOString();
  let md = `# ${sessionTitle}\n\n`;

  // Metadata block
  md += `| Metadata | Value |\n`;
  md += `| :--- | :--- |\n`;
  md += `| **Export Date** | ${timestamp} |\n`;
  md += `| **Workspace ID** | \`${workspaceId}\` |\n`;
  md += `| **Pipeline Mode** | \`${pipelineMode}\` |\n`;
  md += `| **Grounding Strictness** | \`${groundingMode}\` |\n`;
  md += `| **Total Turns** | ${Math.ceil(messages.length / 2)} |\n\n`;
  md += `---\n\n`;

  // Messages
  let turnNumber = 1;
  for (let i = 0; i < messages.length; i++) {
    const msg = messages[i];
    if (msg.role === "user") {
      md += `### Turn ${turnNumber}: Question\n\n`;
      md += `> **User**: ${msg.content}\n\n`;
    } else {
      md += `#### Answer (TitanRAG)\n\n`;
      md += `${msg.content}\n\n`;

      if (msg.citations && msg.citations.length > 0) {
        md += `##### Citations & Grounding Sources\n\n`;
        msg.citations.forEach((c) => {
          const verifiedBadge = c.verified ? "✅ Verified" : "⚠️ Unverified";
          md += `- **[${c.source_index}]** *${c.document_name}* (Page ${c.page_number ?? 1}) — ${verifiedBadge}\n`;
          md += `  > "${c.snippet.replace(/\n/g, " ").trim()}"\n`;
        });
        md += `\n`;
      }
      md += `---\n\n`;
      turnNumber++;
    }
  }

  // Enterprise Disclaimer Stamp
  md += `### Disclaimer\n\n`;
  md += `*Generated by TitanRAG Enterprise Knowledge Engine. Verified with NLI Grounding Guardrails. All citations reference authenticated tenant documents.*\n`;

  return md;
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportChatMarkdown(options: ExportChatOptions) {
  const md = generateMarkdownExport(options);
  const cleanTitle = (options.sessionTitle || "chat-session").replace(/[^a-zA-Z0-9_-]/g, "_");
  const filename = `${cleanTitle}-${new Date().toISOString().slice(0, 10)}.md`;
  downloadFile(md, filename, "text/markdown;charset=utf-8");
}

export function exportChatJson(options: ExportChatOptions) {
  const data = {
    exportedAt: new Date().toISOString(),
    sessionTitle: options.sessionTitle || "TitanRAG Chat Session",
    workspaceId: options.workspaceId,
    pipelineMode: options.pipelineMode,
    groundingMode: options.groundingMode,
    messages: options.messages,
  };
  const jsonStr = JSON.stringify(data, null, 2);
  const cleanTitle = (options.sessionTitle || "chat-session").replace(/[^a-zA-Z0-9_-]/g, "_");
  const filename = `${cleanTitle}-${new Date().toISOString().slice(0, 10)}.json`;
  downloadFile(jsonStr, filename, "application/json;charset=utf-8");
}

export function exportChatPrintPdf(options: ExportChatOptions) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to export chat as PDF/Print.");
    return;
  }

  const timestamp = new Date().toLocaleString();
  const title = options.sessionTitle || "TitanRAG Chat Session";

  let bodyHtml = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          @page { margin: 20mm; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #0f172a;
            line-height: 1.6;
            font-size: 13px;
          }
          h1 { font-size: 20px; color: #0284c7; margin-bottom: 4px; }
          .meta-table {
            width: 100%;
            border-collapse: collapse;
            margin: 16px 0;
            font-size: 12px;
          }
          .meta-table th, .meta-table td {
            border: 1px solid #e2e8f0;
            padding: 6px 10px;
            text-align: left;
          }
          .meta-table th { background: #f8fafc; font-weight: 600; width: 25%; }
          .turn-block {
            margin-bottom: 24px;
            page-break-inside: avoid;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            overflow: hidden;
          }
          .user-q {
            background: #f1f5f9;
            padding: 12px 16px;
            border-bottom: 1px solid #e2e8f0;
            font-weight: 600;
          }
          .assistant-a {
            padding: 16px;
            background: #ffffff;
            white-space: pre-wrap;
          }
          .citations-box {
            margin: 12px 16px 16px;
            padding: 12px;
            background: #f8fafc;
            border: 1px dashed #cbd5e1;
            border-radius: 6px;
            font-size: 11px;
          }
          .citation-item { margin-bottom: 6px; }
          .badge-verified { color: #16a34a; font-weight: bold; }
          .disclaimer {
            margin-top: 32px;
            padding-top: 12px;
            border-top: 1px solid #cbd5e1;
            font-size: 11px;
            color: #64748b;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p style="color:#64748b; font-size:12px; margin:0;">TitanRAG Grounded Intelligence Transcript</p>

        <table class="meta-table">
          <tr><th>Export Date</th><td>${timestamp}</td></tr>
          <tr><th>Workspace</th><td><code>${options.workspaceId || "default"}</code></td></tr>
          <tr><th>Pipeline Mode</th><td><code>${options.pipelineMode || "auto"}</code></td></tr>
          <tr><th>Grounding Mode</th><td><code>${options.groundingMode || "balanced"}</code></td></tr>
        </table>
  `;

  let turn = 1;
  for (let i = 0; i < options.messages.length; i++) {
    const msg = options.messages[i];
    if (msg.role === "user") {
      bodyHtml += `<div class="turn-block"><div class="user-q">User Turn ${turn}: ${escapeHtml(msg.content)}</div>`;
    } else {
      bodyHtml += `<div class="assistant-a">${escapeHtml(msg.content)}</div>`;
      if (msg.citations && msg.citations.length > 0) {
        bodyHtml += `<div class="citations-box"><strong>Sources & Citations:</strong><br/>`;
        msg.citations.forEach((c) => {
          bodyHtml += `<div class="citation-item">[${c.source_index}] <strong>${escapeHtml(c.document_name)}</strong> (P.${c.page_number ?? 1}) - <span class="badge-verified">${c.verified ? "Verified" : "Unverified"}</span><br/><em>"${escapeHtml(c.snippet)}"</em></div>`;
        });
        bodyHtml += `</div>`;
      }
      bodyHtml += `</div>`;
      turn++;
    }
  }

  bodyHtml += `
        <div class="disclaimer">
          Generated by TitanRAG Enterprise Knowledge Engine. Verified with NLI Grounding Guardrails.<br/>
          Confidential - Internal Enterprise Use Only.
        </div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(bodyHtml);
  printWindow.document.close();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
