model_list:
  - model_name: meta/llama-3.2-11b-vision-instruct
    litellm_params:
      model: openai/meta/llama-3.2-11b-vision-instruct
      api_base: "https://integrate.api.nvidia.com/v1"
      api_key: "os.environ/NVIDIA_API_KEY"
  - model_name: deepseek-ai/deepseek-v4-flash-0731
    litellm_params:
      model: openai/meta/llama-3.2-11b-vision-instruct
      api_base: "https://integrate.api.nvidia.com/v1"
      api_key: "os.environ/NVIDIA_API_KEY"
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/meta/llama-3.2-11b-vision-instruct
      api_base: "https://integrate.api.nvidia.com/v1"
      api_key: "os.environ/NVIDIA_API_KEY"
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/nvidia/nemotron-3-embed-1b
      api_base: "https://integrate.api.nvidia.com/v1"
      api_key: "os.environ/NVIDIA_API_KEY"

general_settings:
  master_key: sk-titanrag-litellm-master-key

router_settings:
  routing_strategy: "latency-based-routing"
  redis_host: "redis"
  redis_port: 6379
  redis_password: ""
  timeout: 30
  num_retries: 3
  retry_after: 1
